parameters:
#    jpsmith1981_sg.example.class: jpsmith1981\Bundle\SGBundle\Example

services:
#    jpsmith1981_sg.example:
#        class: %jpsmith1981_sg.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
